import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Aside from './_layouts/Aside'
import Header from './_layouts/Header'
import Providers from '@/contexts/Providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} overflow-hidden h-screen flex flex-col`}>
        <Providers>
          <Header />
          <div className='flex '>
            <Aside />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  )
}
